### ISSUE TITLE
Why the transpose on total_state?

### ISSUE THREAD

**Issue by kasimte** [RunzheYang/MORL#14]
In the multimario double envelope implementation, here,

https://github.com/RunzheYang/MORL/blob/d8ce3e3ec9475940d346ee1fd5ce0da7bde1d2a7/multimario/run_e3c_double.py#L297

, the `total_state` data is transposed like so:

```
            total_state = np.stack(total_state).transpose(
                [1, 0, 2, 3, 4]).reshape([-1, 4, 84, 84])
```

What is the intention here? 

As I understand it, `total_state` is 5 batches of states from the GAE loop prior to the training section, which is then unbatched into a single array of states for processing. But it isn't clear to me what the transpose is there for.

Thanks in advance.

**Comment by RunzheYang** [comment]
I think this would ensure the states are arranged in an order the envelope calculation is straight forward. 


Since we expand the preference by #step x #agents times. Suppose we have 2 agents and there steps in the batch. The preference batch is
_[w1, w1, w1, w1, w1, w1, w2, w2, w2, w2, w2, w2...]_

Before transpose the state is _[#step, #agents, #frame, w, h]_,
if we directly reshape it would become _[s1, u1, s2, u2, s3, u3, ...]_
_s_s indicate agent 1's states and _u_s indicate agent 2's sates.

after transpose it is _[#agents, #state,  #frame, w, h]_
the if we reshape it becomes _[s1, s2, s3, u1, u2, u3, ...]_

**Comment by RunzheYang** [comment]
I think this would ensure the states are arranged in an order the envelope calculation is straight forward:

https://github.com/RunzheYang/MORL/blob/d8ce3e3ec9475940d346ee1fd5ce0da7bde1d2a7/multimario/run_e3c_double.py#L117

Since we expand the preference by #step x #agents times. Suppose we have 2 agents and there steps in the batch. The preference batch is
_[w1, w1, w1, w1, w1, w1, w2, w2, w2, w2, w2, w2...]_

Before transpose the state is _[#step, #agents, #frame, w, h]_,
if we directly reshape it would become _[s1, u1, s2, u2, s3, u3, ...]_
_s_s indicate agent 1's states and _u_s indicate agent 2's sates.

after transpose it is _[#agents, #state,  #frame, w, h]_
the if we reshape it becomes _[s1, s2, s3, u1, u2, u3, ...]_
this is what we want as inputs of `envelope_operator`

**Comment by lesleychou** [comment]
I assume here you meant:
"Before transpose the state is [#**state**, #agents, #frame, w, h]" right?
Or it should be #**step**? 
Sorry but I'm not confident about this...

**Comment by RunzheYang** [comment]
it's #step. basically it's the number of gae steps (`args.num_step`).

**Comment by lesleychou** [comment]
> it's #step. basically it's the number of gae steps (`args.num_step`).

Got it! Thanks much for your super active reply^^

**Comment by kasimte** [comment]
Thanks, @RunzheYang. That was very helpful.
